services:
  server:
    container_name: server
    image: lesta-start-battleship/matchmaking:dev
    build:
      context: ../
      dockerfile: build/server.dockerfile
      target: runner
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - API_GATEWAY_URL=${API_GATEWAY_URL}
      - KAFKA_ADDR=${KAFKA_ADDR}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

