build:
  go build -o ./tmp/server ./server/server.go
  go build -o ./tmp/client ./client/client.go

run-server:
  ./tmp/server

run-random:
  ./tmp/client -path=/matchmaking/random

run-ranked:
  ./tmp/client -path=/matchmaking/ranked

run-custom:
  ./tmp/client -path=/matchmaking/custom
